# -*- coding: utf-8 -*-
"""equifit.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1mOwz58Y3U6fklZD--rWMXCK5ot2RITJK
"""

# 1. Libraries
import pandas as pd
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity

# 2. Load datasets
internships = pd.read_csv("internships preprocessed 1.csv", encoding="utf-8")
candidates = pd.read_csv("preprocessed candidates 1.csv", encoding="utf-8")

print("Head of internships preprocessed dataset:")
print(internships.head())

print("\nHead of preprocessed candidates dataset:")
print(candidates.head())

# 3. TF-IDF on Job Descriptions
tfidf = TfidfVectorizer(stop_words="english")
tfidf_matrix = tfidf.fit_transform(internships["Job_Description"].astype(str)) # Ensure Job_Description is string
internships["tfidf_vector"] = list(tfidf_matrix.toarray())

# 4. Recommendation Function (Updated with Mode and Hybrid Prioritization)
def recommend_internships(candidate_id, top_n=5, weights=(0.5, 0.2, 0.15, 0.15)):
    """
    weights = (skills_weight, sector_weight, location_weight, mode_weight)
    """
    candidate = candidates[candidates["Applicant_ID"] == candidate_id].iloc[0]
    candidate_vec = tfidf.transform([str(candidate["Skills"])]).toarray()
    skills_sim = cosine_similarity(candidate_vec, tfidf_matrix)[0]

    # Sector match
    candidate_sectors = [s.strip() for s in candidate["Sector_Preferences"].split(',')]
    sector_match = internships["Sector"].apply(lambda x: 1 if x in candidate_sectors else 0)

    # Location match
    candidate_locations = [loc.strip() for loc in candidate["Location_Preference"].split(',')]
    location_match = internships["Location"].apply(lambda x: 1 if x in candidate_locations else 0)

    # Mode preference (placeholder logic)
    candidate_mode_preference = 'Remote' if 'Urban' in candidate['Background'] else 'In-person'
    candidate_mode_preferences = [candidate_mode_preference, 'Hybrid']
    mode_match = internships["Mode"].apply(lambda x: 1 if x in candidate_mode_preferences else 0)

    # Weighted score
    scores = (
        weights[0]*skills_sim +
        weights[1]*sector_match +
        weights[2]*location_match +
        weights[3]*mode_match
    )

    internships["Score"] = scores
    internships['Mode_Rank'] = internships['Mode'].apply(
        lambda x: 2 if x == 'Hybrid' else (1 if x in ['Remote', 'In-person'] else 0)
    )

    return internships.sort_values(['Mode_Rank', 'Score'], ascending=[False, False]).head(top_n)[
        ["Internship_ID","Title","Sector","Location","Mode","Industry_Type","Job_Description","Score"]
    ]

# === Example Usage with flexible weights ===
candidate_id = "APP004"

# Default weights
print("🎯 Default Weights (0.3, 0.3, 0.2, 0.2)")
print(recommend_internships(candidate_id, top_n=5, weights=(0.3, 0.3, 0.2, 0.2)))