# -*- coding: utf-8 -*-
"""equifit.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1mOwz58Y3U6fklZD--rWMXCK5ot2RITJK
"""

import pandas as pd
internships = pd.read_csv("internships preprocessed 1.csv")
candidates = pd.read_csv("preprocessed candidates 1.csv")

print("Head of internships preprocessed dataset:")
print(internships.head())

print("\nHead of preprocessed candidates dataset:")
print(candidates.head())

# ================================
# PMIS Internship Recommendation Engine (AI-driven with Mode Boost)
# ================================

# 1. Libraries
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity
import numpy as np

# 2. Load datasets
# Assuming 'candidates' and 'internships' DataFrames are already loaded and preprocessed
# candidates = pd.read_csv("preprocessed candidates 1.csv")
# internships = pd.read_csv("internships preprocessed 1.csv")

# 3. TF-IDF on Job Descriptions and Skills Required
# Combine Job Description and Skills Required for fitting
combined_corpus = internships["Job_Description"].astype(str) + " " + internships["Skills_Required"].astype(str)
tfidf = TfidfVectorizer(stop_words="english")
tfidf_matrix = tfidf.fit_transform(combined_corpus)

# Transform Job Descriptions and Skills Required using the fitted vectorizer
tfidf_matrix_jd = tfidf.transform(internships["Job_Description"].astype(str))
internships["tfidf_vector_jd"] = list(tfidf_matrix_jd.toarray())

tfidf_matrix_skills = tfidf.transform(internships["Skills_Required"].astype(str))
internships["tfidf_vector_skills"] = list(tfidf_matrix_skills.toarray())


# 4. Recommendation Function (Now includes Skills_Required)
def recommend_internships(candidate_id, top_n=5, weights=(0.35, 0.25, 0.15, 0.15, 0.10)):
    """
    weights = (skills_required_weight, jobdesc_weight, sector_weight, location_weight, mode_weight)
    """
    candidate = candidates[candidates["Applicant_ID"] == candidate_id].iloc[0]

    # Candidate skills vector using the fitted vectorizer
    candidate_vec = tfidf.transform([str(candidate["Skills"])]).toarray()

    # Similarity with internship Job Description
    jd_sim = cosine_similarity(candidate_vec, tfidf_matrix_jd)[0]

    # Similarity with internship Skills_Required
    skills_sim = cosine_similarity(candidate_vec, tfidf_matrix_skills)[0]

    # Sector match
    candidate_sectors = [s.strip() for s in str(candidate["Sector_Preferences"]).split(',')]
    sector_match = internships["Sector"].apply(lambda x: 1 if x in candidate_sectors else 0)

    # Location match
    candidate_locations = [loc.strip() for loc in str(candidate["Location_Preference"]).split(',')]
    location_match = internships["Location"].apply(lambda x: 1 if x in candidate_locations else 0)

    # Mode preference (simple rule-based logic)
    candidate_mode_preference = 'Remote' if 'Urban' in str(candidate['Background']) else 'In-person'
    candidate_mode_preferences = [candidate_mode_preference, 'Hybrid']
    mode_match = internships["Mode"].apply(lambda x: 1 if x in candidate_mode_preferences else 0)

    # Weighted score (now includes Skills_Required similarity)
    scores = (
        weights[0]*skills_sim +
        weights[1]*jd_sim +
        weights[2]*sector_match +
        weights[3]*location_match +
        weights[4]*mode_match
    )

    internships["Score"] = scores
    internships['Mode_Rank'] = internships['Mode'].apply(
        lambda x: 2 if x == 'Hybrid' else (1 if x in ['Remote', 'In-person'] else 0)
    )

    return internships.sort_values(['Mode_Rank', 'Score'], ascending=[False, False]).head(top_n)[
        ["Internship_ID","Title","Sector","Location","Mode","Industry_Type",
         "Job_Description","Skills_Required","Score"]
    ]


# === Example Usage with flexible weights ===
candidate_id = "APP005"

print("🎯 Updated Recommendations with Skills_Required included")
print(recommend_internships(candidate_id, top_n=5,
                            weights=(0.3, 0.2, 0.15, 0.25, 0.10)))